// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Link struct {
	ID     int32          `json:"id"`
	Domain sql.NullString `json:"domain"`
}

type Page struct {
	ID            int32          `json:"id"`
	Domain        sql.NullString `json:"domain"`
	Searchdeep    sql.NullInt32  `json:"searchdeep"`
	Maxsearchdeep sql.NullInt32  `json:"maxsearchdeep"`
}

type Pageslink struct {
	ID      int32         `json:"id"`
	PagesID sql.NullInt32 `json:"pages_id"`
	LinksID sql.NullInt32 `json:"links_id"`
}
